### ISSUE TITLE
Assertion sometimes called when used with skim

### ISSUE THREAD

**Issue by ibhagwan** [vijaymarupudi/nvim-fzf#27]
I think this is going to be one of those annoying issues with no clear source, thankfully it’s not that hard to reproduce.

The assertion line that gets called is inside `raw_action` at actions.lua#L52:

https://github.com/vijaymarupudi/nvim-fzf/blob/bd06596e5db8939e6dd5d054c0e52655cf205ee4/lua/fzf/actions.lua#L52

The way to reproduce it is have a preview set to nvim-fzf’s `raw_action` and then hold down either arrow (up/down) in order to move really quick between the lines (thus calling the action multiple times really quick), note that this **only happens with `sk`** and not fzf.

Now I’m not sure if it will happen with a minimal fast preview action because I haven’t seen this happen before. I just added new functionality to fzf-lua with a builtin previewer, it reads the files into the buffer and enables syntax highlighting (I.e treesitter) so the action is a bit heavier than most, if you install skim and my plug-in and hold down the down arrow key you’ll be able to reproduce this pretty quickly.

Alternatively, if you believe the assertion is useless and there is a legitimate reason for the pipe to err there maybe we can just get rid of the assertion?

**Comment by vijaymarupudi** [comment]
* User presses down arrow
* Neovim starts doing the syntax highlighting and takes time to do so
* The user presses down arrow before neovim is done, nevertheless tree-sitter completes and writes to the pipe
* The pipe does not exist anymore, since skim has closed the preview pipe. This triggers the error.

This sequence of errors make sense to me. I will remove the assert, as this is the only feasible error that can occur that I can think of, and there's a very valid use case for ignoring.

I suspect the difference between fzf and skim is how they wait for the preview program (I have not tested this). I suspect that fzf waits for the preview program to exit before closing the pipe, but skim probably closes it as soon as it doesn't need the output.

Regardless, https://github.com/vijaymarupudi/nvim-fzf/commit/7c06b1ef15be6b7f9a24439025e095cadbee0669 should fix the issue!

**Comment by ibhagwan** [comment]
Works great now, ty!
