### ISSUE TITLE
quickfix integration?

### ISSUE THREAD

**Issue by alok** [vijaymarupudi/nvim-fzf#9]
selecting multiple should allow putting them in quickfix/location list

**Comment by vijaymarupudi** [comment]
Hi Alok!

Your issue is probably about the https://github.com/vijaymarupudi/nvim-fzf-commands repository. Could you post this issue there? I can't transfer issues across repos. In addition, could you mention which command you want this feature added to? I'm fairly certain it's `rg`, but just to confirm.
